language: node_js
node_js:
  - 'node'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-event-manager
  on:
    branch: master
